language: node_js
node_js:
  - "node"
before_script:
  - npm install -g browserstack-runner
  - npm run build
script:
  - browserstack-runner
  - BROWSERSTACK_JSON=test/ie8/browserstack.json browserstack-runner
